### ISSUE TITLE
gemini3d.msis.msis_setup error

### ISSUE THREAD

**Issue by mattzett** [gemini3d/pygemini#8]
```
msisdata=gemini3d.msis.msis_setup(cfg,xg)
HDF5-DIAG: Error detected in HDF5 (1.12.1) thread 0:
  #000: H5F.c line 620 in H5Fopen(): unable to open file
    major: File accessibility
    minor: Unable to open file
  #001: H5VLcallback.c line 3502 in H5VL_file_open(): failed to iterate over available VOL connector plugins
    major: Virtual Object Layer
    minor: Iteration failed
  #002: H5PLpath.c line 579 in H5PL__path_table_iterate(): can't iterate over plugins in plugin path '(null)'
    major: Plugin for dynamically loaded library
    minor: Iteration failed
  #003: H5PLpath.c line 620 in H5PL__path_table_iterate_process_path(): can't open directory: /usr/local/hdf5/lib/plugin
    major: Plugin for dynamically loaded library
    minor: Can't open directory or file
  #004: H5VLcallback.c line 3351 in H5VL__file_open(): open failed
    major: Virtual Object Layer
    minor: Can't open object
  #005: H5VLnative_file.c line 97 in H5VL__native_file_open(): unable to open file
    major: File accessibility
    minor: Unable to open file
  #006: H5Fint.c line 1835 in H5F_open(): unable to open file: name = 'inputs/msis_setup_in.h5', tent_flags = 0
    major: File accessibility
    minor: Unable to open file
  #007: H5FD.c line 723 in H5FD_open(): open failed
    major: Virtual File Layer
    minor: Unable to initialize object
  #008: H5FDsec2.c line 355 in H5FD__sec2_open(): unable to open file: name = 'inputs/msis_setup_in.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0
    major: File accessibility
    minor: Unable to open file
 h5fortran:ERROR: inputs/msis_setup_in.h5: error code           -1
ERROR STOP 
Traceback (most recent call last):

  File "<ipython-input-13-818307e13591>", line 1, in <module>
    msisdata=gemini3d.msis.msis_setup(cfg,xg)

  File "/Users/zettergm/Projects/pygemini/src/gemini3d/msis.py", line 98, in msis_setup
    raise RuntimeError(

RuntimeError: MSIS failed to run: return code 1. See console for additional error info.
```

**Comment by mattzett** [comment]
The file it is looking for appears to be generated in ~/inputs/ rather than wherever the code is searching for it...

**Comment by scivision** [comment]
I added code to Gemini3D and PyGemini to give a better feedback of what went wrong. 

I think the root cause is that msis_setup in Python didn't use expanduser() on the paths; it was assuming they came from another part of PyGemini where expanduser() had already been done. I added this path processing now.

Please reopen if it is still happening
