### ISSUE TITLE
Recent changes creating problem with cmake

### ISSUE THREAD

**Issue by mattzett** [gemini3d/pygemini#9]
MacOS with cmake installed via brew:

```
gemini3d.model.setup("./config.nml","~/simulations/GDI_toyproblem/")
Traceback (most recent call last):

  File "<ipython-input-31-690f86472a9f>", line 1, in <module>
    gemini3d.model.setup("./config.nml","~/simulations/GDI_toyproblem/")

  File "/Users/zettergm/Projects/pygemini/src/gemini3d/model.py", line 143, in setup
    interp(cfg)

  File "/Users/zettergm/Projects/pygemini/src/gemini3d/model.py", line 175, in interp
    equilibrium_resample(cfg, xg)

  File "/Users/zettergm/Projects/pygemini/src/gemini3d/plasma.py", line 39, in equilibrium_resample
    extract_zst(p["eq_archive"], p["eq_dir"])

  File "/Users/zettergm/Projects/pygemini/src/gemini3d/archive.py", line 33, in extract_zst
    subprocess.check_call([cmake.exe(), "-E", "tar", "xf", str(archive)], cwd=out_path)

  File "/Users/zettergm/Projects/pygemini/src/gemini3d/cmake/__init__.py", line 20, in exe
    raise FileNotFoundError("CMake not found.  Try:\n    pip install cmake")

FileNotFoundError: CMake not found.  Try:
    pip install cmake
```

**Comment by scivision** [comment]
does Terminal `which cmake` show anything?

**Comment by scivision** [comment]
I try to look in default prefix directories: https://github.com/gemini3d/pygemini/commit/304bb7f1bc37fad98103934738447f4f4f203625

I had to do this for MatGemini because Matlab wasn't passing along PATH on MacOS. Did this help?

**Comment by mattzett** [comment]
Yes thank you.
